"use strict";

module.exports.plugins = [
	require("remark-lint"),
	require("remark-preset-lint-markdown-style-guide"),
	[require("remark-lint-blockquote-indentation"), 2],
	[require("remark-lint-code-block-style"), "fenced"],
	[require("remark-lint-definition-case"), false],
	[require("remark-lint-definition-spacing"), true],
	[require("remark-lint-emphasis-marker"), "*"],
	[require("remark-lint-fenced-code-flag"), {"allowEmpty": true}],
	[require("remark-lint-fenced-code-marker"), "`"],
	[require("remark-lint-file-extension"), "md"],
	[require("remark-lint-final-definition"), false],
	[require("remark-lint-hard-break-spaces"), true],
	[require("remark-lint-heading-increment"), true],
	[require("remark-lint-heading-style"), "atx"],
	[require("remark-lint-link-title-style"), "\""],
	[require("remark-lint-list-item-content-indent"), 2],
	[require("remark-lint-list-item-indent"), "space"],
	[require("remark-lint-list-item-spacing"), false],
	[require("remark-lint-maximum-heading-length"), 60],
	[require("remark-lint-maximum-line-length"), 140],
	[require("remark-lint-no-auto-link-without-protocol"), true],
	[require("remark-lint-no-blockquote-without-marker"), true],
	[require("remark-lint-no-consecutive-blank-lines"), false],
	[require("remark-lint-no-duplicate-headings"), false],
	[require("remark-lint-no-emphasis-as-heading"), true],
	[require("remark-lint-no-file-name-articles"), false],
	[require("remark-lint-no-file-name-consecutive-dashes"), true],
	[require("remark-lint-no-file-name-irregular-characters"), true],
	[require("remark-lint-no-file-name-mixed-case"), false],
	[require("remark-lint-no-file-name-outer-dashes"), true],
	[require("remark-lint-no-heading-punctuation"), false],
	[require("remark-lint-no-inline-padding"), true],
	[require("remark-lint-no-literal-urls"), true],
	[require("remark-lint-no-multiple-toplevel-headings"), true],
	[require("remark-lint-no-shell-dollars"), false],
	[require("remark-lint-no-shortcut-reference-image"), true],
	[require("remark-lint-no-shortcut-reference-link"), true],
	[require("remark-lint-no-table-indentation"), true],
	[require("remark-lint-ordered-list-marker-style"), "."],
	[require("remark-lint-ordered-list-marker-value"), "ordered"],
	[require("remark-lint-strong-marker"), "*"],
	[require("remark-lint-table-cell-padding"), "consistent"],
	[require("remark-lint-table-pipe-alignment"), false],
	[require("remark-lint-table-pipes"), true],
	[require("remark-lint-unordered-list-marker-style"), "*"],
	[require("remark-lint-checkbox-character-style"), {"checked": "x"}],
	[require("remark-lint-checkbox-content-indent"), true],
	[require("remark-lint-final-newline"), true],
	[require("remark-lint-first-heading-level"), true],
	[require("remark-lint-list-item-bullet-indent"), true],
	[require("remark-lint-no-duplicate-definitions"), true],
	[require("remark-lint-no-heading-content-indent"), true],
	[require("remark-lint-no-heading-indent"), true],
	[require("remark-lint-no-tabs"), true]
];
